version: "3.7"

services:
  
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo
    ports:
      - 5432:5432

  db-ui:
    container_name: postgres-io
    image: adminer
    restart: always
    ports:
      - 8080:8080